### ISSUE TITLE
Cypress 13.0, cannot upload results to test rail

### ISSUE THREAD

**Issue by VoorheesM** [boxblinkracer/cypress-testrail#38]
when running a test the following message is desplayed: 

#TestRail >> Sending case results to run R563: C135 
  Could not send list of TestRail results: 400 Bad Request >> Field :results.elapsed is not in a valid time span format.

this was not that case right before updating to cypress 13.0 so it looks like something was changed there causing this issue

**Comment by boxblinkracer** [comment]
Hi there

oh ok, thank you so much for letting me know
I'll upgrade our cypress project and give it a try

**Comment by M4xymS** [comment]
As a temporary solution, simply change the TestData constructor. @VoorheesM #39 

#39

**Comment by harishigg** [comment]
Having same issue "Could not send list of TestRail results: 400 Bad Request >> Field :results.elapsed is not in a valid time span format."

**Comment by boxblinkracer** [comment]
Hi there

has been fixed with 2.8.1,
forgot to mention it here

also current dev-master has a fix for the broken screenshots (which also changed in cypress 13 haha)

**Comment by natalivoloshyn** [comment]
Hi there,
This issue is still reproducible on 2.8.2
We run tests using tag - so not all tests are launched. Previously results of Pending tests were not pushed to TestRail.
![image](https://github.com/boxblinkracer/cypress-testrail/assets/110406373/90690ac2-d17e-4c05-9ab9-e5b6c7121fe7)

**Comment by boxblinkracer** [comment]
hi therethank you so muchyeah theres a new casesomehow NANs is a value insideso i updated to allow the check if the field doesnt even exist in cypress. but in ur case it exists but with an invalid value i guess thats maybe only with a special combination in any wayi can fix that. shouldnt be hardthx for ur help on that :)On Dec 29, 2023, at 12:06 PM, natalivoloshyn ***@***.***> wrote:﻿
Hi there,
This issue is still reproducible on 2.8.2
We run tests using tag - so not all tests are launched. Previously results of Pending tests were not pushed to TestRail.
image.png (view on web)

**Comment by boxblinkracer** [comment]
ok
I found it with a new jest test 
pretty sure undefined happens, ill add a fix

<img width="921" alt="Screenshot 2023-12-29 at 16 28 47" src="https://github.com/boxblinkracer/cypress-testrail/assets/5579326/9c03197f-2e9e-4ae8-b74c-c0ecd2a633f6">

**Comment by boxblinkracer** [comment]
should work now,
can you give it a try with the latest dev-master
(please also note, axios has been updated, so you might need to reinstall node-modules if sth is weird)

**Comment by natalivoloshyn** [comment]
Hello,
Unfortunatelly this issue is still present if there are 3 and more tests
![image](https://github.com/boxblinkracer/cypress-testrail/assets/110406373/28bc70cb-ae7b-43d8-a995-2b56e103c701)

Please take a look

**Comment by boxblinkracer** [comment]
Hi

thanks for reporting this

I've found indeed a scenario with your description,
so in cypress 13, skipped tests have a duration of "0". Unfortunately because of a not-so-good-implicit if (data.duration) check, it went into checking attempt array from old Cypress <= v12...which of course didnt work either...so "NaN" was back as value

in the end a single jest-unit test was missing and showed the error

i've restructured it a bit more to cover more cases and its working now for me

can you check out dev-master and tell me if its working?

sorry for the inconvenience

**Comment by natalivoloshyn** [comment]
> dev-master

hi,

we have tested this fix and it work great 👌
Thank you very much for it. 
we are waiting for the next release ❤️

**Comment by boxblinkracer** [comment]
perfect
thanks for the feedback

release will come soon...fixing something else and then :)

**Comment by boxblinkracer** [comment]
released with 2.10.0
